# Generated by Django 4.2.19 on 2025-08-04 21:32

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default='User', help_text='Display name (letters only, max 15 characters)', max_length=15)),
                ('beer', models.IntegerField(default=0, help_text='Number of Beers/Seltzers drank (17 ml alcohol per beer)')),
                ('floco', models.IntegerField(default=0, help_text='Number of Flocos (43 ml alcohol per shot)')),
                ('rum', models.IntegerField(default=0, help_text='Number of rum shots (9 ml alcohol per shot)')),
                ('whiskey', models.IntegerField(default=0, help_text='Number of whiskey shots (14 ml alcohol per shot)')),
                ('vodka', models.IntegerField(default=0, help_text='Number of vodka shots (18 ml alcohol per shot)')),
                ('tequila', models.IntegerField(default=0, help_text='Number of tequila shots (23 ml alcohol per shot)')),
                ('shotguns', models.IntegerField(default=0, help_text='Number of shotguns')),
                ('snorkels', models.IntegerField(default=0, help_text='Number of snorkels')),
                ('thrown_up', models.IntegerField(default=0, help_text='Times thrown up')),
                ('xp', models.IntegerField(default=0, help_text='User XP')),
                ('rank', models.CharField(default='Bronze', help_text='User rank', max_length=50)),
                ('friends', models.ManyToManyField(blank=True, to='accounts.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to='accounts.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to='accounts.profile')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to='accounts.profile')),
            ],
            options={
                'unique_together': {('from_user', 'to_user')},
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=accounts.models.current_log_date, help_text='Log date (3 AM to 3 AM)')),
                ('beer', models.PositiveIntegerField(default=0)),
                ('floco', models.PositiveIntegerField(default=0)),
                ('rum', models.PositiveIntegerField(default=0)),
                ('whiskey', models.PositiveIntegerField(default=0)),
                ('vodka', models.PositiveIntegerField(default=0)),
                ('tequila', models.PositiveIntegerField(default=0)),
                ('shotguns', models.PositiveIntegerField(default=0)),
                ('snorkels', models.PositiveIntegerField(default=0)),
                ('thrown_up', models.PositiveIntegerField(default=0)),
                ('xp', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='accounts.profile')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('profile', 'date')},
            },
        ),
    ]
