# Generated by Django 4.2.19 on 2026-04-28 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='monthly_rank',
            field=models.CharField(default='Bronze', help_text='Current month rank (resets 1st of each month)', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='yearly_rank',
            field=models.CharField(default='Bronze', help_text='Current calendar year rank (resets Jan 1)', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rank',
            field=models.CharField(default='Bronze 1', help_text='Lifetime sub-rank', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='xp',
            field=models.IntegerField(default=0, help_text='Lifetime XP'),
        ),
        migrations.CreateModel(
            name='MonthlyRankHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('rank', models.CharField(max_length=50)),
                ('xp', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_rank_history', to='accounts.profile')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('profile', 'year', 'month')},
            },
        ),
    ]
