# Generated by Django 4.2.19 on 2026-05-15 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_monthly_rank_profile_yearly_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tokens',
            field=models.IntegerField(default=0, help_text='Available token balance'),
        ),
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('earn', 'Earn'), ('spend', 'Spend')], max_length=5)),
                ('amount', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('balance_after', models.IntegerField(help_text='Token balance after this transaction')),
                ('competition_id_ref', models.IntegerField(blank=True, help_text='Optional competition ID this relates to', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_transactions', to='accounts.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
